name: Java Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create output directory
        run: mkdir -p out

      - name: Compile Java files
        run: javac -d out Main.java models/PomodoroTime.java services/File.java

      - name: Package JAR
        run: jar cfm PomodoroCalculator.jar manifest.txt -C out .

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroCalculator-JAR
          path: PomodoroCalculator.jar

  build-exe:
    runs-on: windows-latest
    needs: build-jar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: PomodoroCalculator-JAR

      - name: Create EXE with jpackage
        run: |
          jpackage --input . --name PomodoroCalculator --main-jar PomodoroCalculator.jar --main-class Main --type exe

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroCalculator-EXE
          path: PomodoroCalculator\PomodoroCalculator.exe

  build-deb:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: PomodoroCalculator-JAR

      - name: Create DEB with jpackage
        run: |
          jpackage --input . --name PomodoroCalculator --main-jar PomodoroCalculator.jar --main-class Main --type deb

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroCalculator-DEB
          path: PomodoroCalculator*.deb

  build-pkg:
    runs-on: macos-latest
    needs: build-jar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: PomodoroCalculator-JAR

      - name: Create PKG with jpackage
        run: |
          jpackage --input . --name PomodoroCalculator --main-jar PomodoroCalculator.jar --main-class Main --type pkg

      - name: Upload PKG artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroCalculator-PKG
          path: PomodoroCalculator*.pkg

  build-rpm:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: PomodoroCalculator-JAR

      - name: Create RPM with jpackage
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          jpackage --input . --name PomodoroCalculator --main-jar PomodoroCalculator.jar --main-class Main --type rpm

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroCalculator-RPM
          path: PomodoroCalculator*.rpm

  build-appimage:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: PomodoroCalculator-JAR

      - name: Create AppImage with jpackage
        run: |
          jpackage --input . --name PomodoroCalculator --main-jar PomodoroCalculator.jar --main-class Main --type app-image

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroCalculator-AppImage
          path: PomodoroCalculator/app/